# Generated by Django 3.2.7 on 2021-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendfunding', '0002_auto_20210908_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.AddField(
            model_name='goal',
            name='person',
            field=models.ManyToManyField(related_name='person', to='friendfunding.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
