# Generated by Django 3.2.7 on 2021-09-12 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendfunding', '0003_auto_20210912_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goal',
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='friendfunding.user'),
            preserve_default=False,
        ),
    ]
