# Generated by Django 3.2.7 on 2021-09-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendfunding', '0006_auto_20210913_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ManyToManyField(to='friendfunding.User'),
        ),
    ]
