# Generated by Django 3.2.7 on 2021-09-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendfunding', '0009_alter_goal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
